### ISSUE TITLE
Delete a part of intermediate files if rerun dsc?

### ISSUE THREAD

**Issue by mengyin** [stephenslab/dsc2#15]

**Comment by gaow** [comment]
Thanks Mengyin for your suggestions. So the proposed interface is a `-c / --clean` option such that DCS2 will check and remove all irrelevant files in output folder if no parameter is passed to it. Otherwise only clean output from steps specified. I should comment that normally there is no need to clean up specific step because DSC2 will track the changes in your source code, input file and parameters and automatically rerun if there is a change. You just remember to run `-c` to remove trash every now and then. However sometimes when changes occur outside these subjects, e.g., updates in dependent libraries or other loose scripts your computational routine depends on, then it is necessary to pin-point to and delete the step you want to rerun.

**Comment by gaow** [comment]
Implemented

**Comment by gaow** [comment]
I'm reopening this issue because there may be situation when we want to remove a (large intermediate) file yet do not want to trigger a rerun. In that case we'd like to use a different command option. I suggest that we:

1. `--clean` without argument will remove untracked intermadiate files, eg. those files specified by `File(.ext)` but does not show up in `output` thus not a pipeline variable
2. `--clean module` with argument being a module's name will remove all output file produced by that module, yet will not trigger a rerun.
3. `--clean module -f ` adds a `--force` switch to it, so that all files produced by that module are removed and it will later trigger a rerun.

I'm not sure if we should use `--purge` for 3. I propose `--clean ... -f` because `-f` is an existing switch for force rerun DSC. But it is not utilized in this context and we may save us from a new option. But it may be less intuitive.

**Comment by gaow** [comment]
Implemented `purge` (result in behavior 1 and 3 above) and `replace` (result in behavior 2 above) options for `--remove` command.
