### ISSUE TITLE
dsc2 doesn't like R logical objects

### ISSUE THREAD

**Issue by dcgerard** [stephenslab/dsc2#24]
# Files
[dsc_error.zip](https://github.com/stephenslab/dsc2/files/350274/dsc_error.zip)

# Code
``` shell
dsc_error$ dsc exec settings.dsc
INFO: Constructing DSC from settings.dsc ...
INFO: DSC exported to settings.html
INFO: Building output database dsc_result.rds ...
INFO: Elapsed time 0.400 seconds.
ERROR: 'list' object has no attribute 'shape'
ERROR: 'list' object has no attribute 'shape'
```

**Comment by gaow** [comment]
The problem occurs in the final step where I had to manually guess the data types in order to load to Python to build the output database. I took for granted in my code that Boolean vector is just Integer vector. It turns out R stores them as different types and forcefully converting R's Boolean to Python's Integer via rpy2 interface will result in a string not integers. The patch fixed the problem by converting from Boolean to Int in R then load it to Python.
