### ISSUE TITLE
dsc2 doesn't like R NULL objects

### ISSUE THREAD

**Issue by dcgerard** [stephenslab/dsc2#25]
# File
[dsc_null_error.zip](https://github.com/stephenslab/dsc2/files/350373/dsc_null_error.zip)

# Code
``` shell
dsc_null_error$ dsc exec settings.dsc
INFO: Constructing DSC from settings.dsc ...
INFO: DSC exported to settings.html
INFO: Building output database dsc_result.rds ...
INFO: Elapsed time 0.402 seconds.
ERROR: 'list' object has no attribute 'shape'
ERROR: 'list' object has no attribute 'shape'
```

**Comment by gaow** [comment]
This is tricky. This patch b994d884f0be0c997b9d4971aecc956e716b27ac currently ignores NULL results. But later today I'll try to convert NULL to NA first and throw an error message when I detect problematic dimensions when combing multiple data. 

Same as #24 The problem is again in building the final data base with Python. Python / Numpy does not have NULL or NA types. All it has is NaN. So:

## NA
For NA data in R I convert them to NaN when generating the query database.

## NULL
NULL in return may result in undesirable behavior. For example in one data set: 

```r
res <- c(1, 1)
```
you end up with a vector of `1, 1`. But if the return in another data set:

```r
res <- c(NULL, 1)
```
then you end up with a scale of `1` because NULL will be ignored. The right way to do this for the 2nd data set is 

```r
res <-c(NA, 1)
```
So that DSC2 can properly put together results from different parameter combinations of the same step into a table format. 

But DSC2 has no control over user's behavior. Later today I'll change the DSC2 code such that it converts NULL to NA when the return is NULL; and it will throw an error message when down the line it runs into an issue trying to make a table out of different data-sets, for example, it will complain about `NA` being different in length compared to `1 1`.

**Comment by gaow** [comment]
Implemented as proposed above. Let me know if you dislike the behavior @dcgerard
