### ISSUE TITLE
pip install dsc does not work on Mac OS X

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc2#46]
```
$ pip --version
pip 9.0.1 from /Users/pcarbo/anaconda3/lib/python3.5/site-packages (python 3.5)
$ pip install dsc
Collecting dsc
  Using cached dsc-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9b/ck4lp8s140lcksryyh4dppdr0000gn/T/pip-build-j7ycl064/dsc/setup.py", line 15, in <module>
        jquery = open('dsc/asset/jquery-1.10.1.min.js').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'dsc/asset/jquery-1.10.1.min.js'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9b/ck4lp8s140lcksryyh4dppdr0000gn/T/pip-build-j7ycl064/dsc/
```

**Comment by gaow** [comment]
I'll have to move these assets elsewhere as the path for the tmp files is apparently not tractable on Mac. I'll put it to a URL and wget from there, or actually source it via `https`

**Comment by gaow** [comment]
@pcarbo when you get a chance would you test if it now works on Mac? It's just `pip3 install dsc`. I still have not got that iMac for a test. If it works, would you tell me the command to install `pip3` on Mac so that I can update the documentation? I guess it is something like `brew install pip3`? I understand you use anaconda but perhaps many people do not. So I'll just put a `brew` command on the wiki for now and see if Mac people run into problems that way. Thanks!

**Comment by pcarbo** [comment]
@gaow I think it worked. I didn't get an error. Attached is the output from running `pip install dsc`.
[pip_install_dsc.txt](https://github.com/stephenslab/dsc2/files/759615/pip_install_dsc.txt)

I think it may be worth mentioning Anaconda as an option. It was very easy to install from [here](http://www.continuum.io/downloads).

I haven't installed python (and pip) using Homebrew, but it should be possible to do so with `brew install python3`:

```bash
$ brew info python3
python3: stable 3.6.0 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
```

Hope that is helpful.
