### ISSUE TITLE
Add functionality to run subscript from the command line

### ISSUE THREAD

**Issue by jhsiao999** [stephenslab/dsc2#5]
Re. what we discussed earlier today. Instead of making settings.yaml for many combinations of the scenarios*methods*score, perhaps we can have one main settings.yaml and run a subset of the combinations through command line. 

(sim[1]*est[1], sim[2], est[2]) * mse

**Comment by gaow** [comment]
I'm not sure if it is good idea to allow for only this feature, or to allow for passing any DSC parameters from the commandline, for example, 
```
dsc execute config.yml -c "DSC::run::sim[1]* est[1] * mse" "simulate::exec::rnorm.R"
```
And whether or not this is a good interface for it. My main concern is that this might harm reproducibility because you'll end up having the same DSC end database for your result with different parameter settings. Implementation is easy but we may want to figure out how to prevent this design from causing chaos.

**Comment by gaow** [comment]
In order to force reproducibilty I decide not to allow for input of any parameters. But because input sequences do not change any parameters or files defined by DSC script, I have allowed for the possibility to override default DSC sequence via `-s` option. Here is an example on the Quick Start tutorial:

```
[GW] dsc execute settings.yaml -s 'simulate[1] * estimate[1]'
INFO: Constructing DSC from settings.yaml ...
INFO: Load command line DSC sequence: simulate[1] * estimate[1]
INFO: Running DSC jobs ...
simulate_1+estimate_1: 100% [============================] 2 0.3/s in 00:00:06
DSC: 100% [==========================================] 1 0.2/s in 00:00:06
INFO: Building summary database dsc_result.csv.gz & dsc_result.db ...
INFO: DSC complete!
INFO: Elapsed time 6.696 seconds.
```
