### ISSUE TITLE
--extract should propagate multiple variables from multiple blocks to "flat" data structure

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc2#55]
Example of call that `dsc` should support:

`dsc settings.dsc --extract mse:mse,simulate:n,simulate:true_mean`

Proposal is to save results to a list data structure in which each entry corresponds to a single variable, e.g., 

```
> out
$`mse:mse`
 [1]  2.3531  1.5386 -1.1397  0.3265 -1.2989 -0.5772  0.4181 -0.4103 -1.9906
[10] -0.8631

$`simulate:n`
 [1]  1  2  3  4  5  6  7  8  9 10

$`simulate:true_mean`
 [1] 0 0 0 0 0 1 1 1 1 1
```

And more complex return values (e.g., 2 x 2 matrices) will be stored in a list object within the main list.

**Comment by stephens999** [comment]
this is a great step forward. 

Can you see a way to easily combine this with a simple way to name complex objects?
eg when we define g=normalmix(xxx), you'd like to have a way to give that a name and the
extracted output be indexed by that name rather than by normalmix(xxx)...

**Comment by gaow** [comment]
Yes, this is supported -- we should show examples of these applications after this ticket is closed, hopefully tomorrow.

**Comment by gaow** [comment]
With this patch, one can run:

```
$ dsc settings.dsc --extract beta_score:result shrink:beta_est shrink:pi0_est --extract_from beta_score --tags "An && ash_n" "An && ash_nu"
Extracting: 100% [=======================] 7 5.7/s in 00:00:01
INFO: Data extracted to dsc_result.extracted.rds for annotations An && ash_n, An && ash_nu for DSC result beta_score.
INFO: Elapsed time 1.562 seconds.
```

and the outcome:

![2017-02-02-23-32-31_scrot](https://cloud.githubusercontent.com/assets/917985/22580672/e917cffe-e99f-11e6-8ed1-1f69df66da60.png)

The results are propagated such that each element in the list now has equal length. The caveat is that now everything is in R's `list` regardless of data type. For example even for simple data types, e.g. a number, the outcome are lists:

```
￼> dat$An_ash_n_beta_score_result
[[1]]
[1] 0.7736099

[[2]]
[1] 0.5789447

[[3]]
[1] 0.71792

[[4]]
[1] 0.5506716

[[5]]
[1] 0.4610809

> dat$An_ash_nu_beta_score_result
[[1]]
[1] 0.7842367

[[2]]
[1] 0.5757998

[[3]]
[1] 0.7159448

[[4]]
[1] 0.5536478

[[5]]
[1] 0.4598015
```

I do not think it is a big issue though, because it is most trivial to use R functions such as `c`, `rbind`, `data.frame` etc to create vectors, matrix, data frame, etc. We can write tips in our documentation, or handle it ourselves in shinydsc.
