### ISSUE TITLE
A super block layer in DSC logic?

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#69]
This splits from #67 

## Goal
Possibly adding another layer of class to group tasks? But we now already have quite a few. The different pieces in DSC goes (from small to large,  `->` indicates: "collectively called" ):

```
task/job/computational incidence -> step -> block -> sequence / pipeline -> benchmark
```
Now we are talking about having a "super block", something like:

```
task/job/computational incidence -> step -> block -> class? -> sequence / pipeline -> benchmark
```

## Pros

Makes a pipeline somewhat more clear logically.

## Cons

Adds complications. Plus this "super block" concept can already be implemented in annotation but it is more a flavor not a requirement so either one such "feature" has to go.

**Comment by jdblischak** [comment]
One thought for now after reading through the current terminology page. We need to distinguish between terms that describe the implementation via dsc2 and the terms that describe larger meta-concepts.

For example, I view the term "DSC block" similar to "DSC script". They are both referring to how dsc2 implements the benchmark. Thus I don't think "block" belongs in the hierarchy you have defined. A "block" can be one thing (e.g. method or scoring function) or a series of mutually exclusive things. Since it is up to the user to decide how to organize the blocks, it could be different things. For example, if all the methods have the same input parameters, then the block could be the "class" we are referring to.

```
methods:
  exec: method1.R, method2.R
  params: x, y
  ...
```

Just a suggestion, maybe methods with different inputs could be nested in a block:

```
methods:
  method1:
    exec: method1.R
    param: x, y
    ...
  method2:
    exec: method2.R
    param: x, y, z
    ...
```

This would make it so that the "block" was always the same as the conceptual "class" no matter how the user chooses to organize them.

**Comment by gaow** [comment]
Nested class might be a way to go but what if a class belongs to two such super classes? Or we disallow that by design?

**Comment by jdblischak** [comment]
Could you give a hypothetical example? In the simple case where there are scenarios to create data, methods to analyze the data, and scores to assess the methods, I don't see any of these could be shared across these 3 distinct roles.

**Comment by gaow** [comment]
Many things can happen in between data creation, analyzing and scoring. For example we have:

```
get_data * filter_data * analyze ....
```

and 

```
get_data * transform_data * filter_data * analyze
```
and
```
get_data * transform_data * filter_data_again * analyze
```
and
```
get_data * transform_data * filter_data * filter_data_again * analyze
```
and

```
get_data * filter_data * transform_data * filter_data_again * analyze

```
Then  how do we organize these data torturing technique in a nice nested fashion?

**Comment by jdblischak** [comment]
So in your example, the problem is that some filtering functions could be shared between the classes `filter_data` and `filter_data_again`?

**Comment by gaow** [comment]
Well that'd be the problem, if I do define `filter_data` and `filter_data_again` as separate classes. But the bigger problem is that this hypothetical example gives a situation when these filters are equivalent, but not mutually exclusive. There is also no clear order in which they should disappear in the sequence. I think DSC was initially designed to handle something very arbitrary compared to what dscr can do. This would be one typical case.

**Comment by jdblischak** [comment]
It's not clear to me how the issue of "order in the sequence" relates to the idea of a "class" or "super block". My suggestion was trying to make it so that the two ways of defining steps (1 - define all related methods in one block; 2 - define related methods in separate blocks) could be handled in the same way (and using the same meta-concept terminology).

Or in other words, have some mechanism for combining blocks into steps when that makes sense. For example in the [ashr example](https://stephenslab.github.io/dsc-wiki/doc/tutorials/Intermediate_R_1.html) the two scores are defined in separate blocks, but they are both scores. Having to write out each score would get very tedious if there were many more, so it would be convenient to define these as one "step/class/etc."

```
scores: beta_score, pi0_score

DSC:
      run: simulate *
           shrink *
           scores
```

And for some steps, like your filtering example, it may not make sense to combine them, so they can be specified separately in the `run` command.

**Comment by pcarbo** [comment]
Please refer to [my comments on programming language terminology](https://github.com/stephenslab/dsc2/issues/68#issuecomment-284879889) which may help to provide some background for this discussion. 

The idea of combining or grouping blocks in specified ways is related to the notion of "first-order" functions, and so it is unsurprising that this issue would arise; that is, the idea that we might have some code pattern that applies some to-be-determine function within this pattern. Similarly, we might have a usage pattern in a DSC (e.g., how it is evaluated in a pipeline) that is common to several blocks/modules, and we would like to encode this to make our DSC specification more concise.

**Comment by stephens999** [comment]
I think for now we can avoid defining such classes and super-blocks.

They may be useful for edge cases, and might also end up being
useful for clarifyign the logic and/or making the YAML easier to read.
But my current vision is that
we can do most of the things we want in terms of extracting information
from pipelines without explicitly introducing any terminology for this
right now.

**Comment by gaow** [comment]
Discussion formalized at:

https://github.com/stephenslab/dsc-wiki/blob/master/development/finalized_terminology_and_extraction.md
