### ISSUE TITLE
Extraction syntax

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc2#72]
I'm starting a new ticket for this as i think it is separate from the meta-data issue
and the previous issue has become about meta-data/tables etc.

I've outlined potential extractions in R
[here](https://github.com/stephenslab/dsc-wiki/blob/master/development/initial_thoughts_on_terminology_and_extraction.md#extracting-information-about-a-pipeline). But maybe it is helpful to talk about a potential
command line syntax because I think @gaow may find that more appealing (both to use and implement).

I find it easiest to start by thinking of examples.

How about something like

```
-e (norm,t,cauchy) .name .param:n WHERE .param:n IN (10,100),
(mean,median) .name,
(score_beta) .name .output:score
```

here there are three elements to the extraction statement (one on each line).
Each element starts with a list of module names, then a list of things to be extracted
from module instances with one of those names, and optionally a selection statement (WHERE...)

Here .name, .param and .output are "keywords" which I've indicated with the . 
Recall that every module instance has a name and param (from its definition) and output values... 

To simplify, think for a moment that the result of this query will be a table/dataframe, with one row per pipeline instance. (For more complex queries involving non-atomic results we will need to use a list).

Each element of the extraction defines a subset of pipeline instances and some columns of output to be produced. The overall result will be the intersection of the rows and union of the columns.

Each element starts with a list of module names.
The idea is that this list should involve mutually exclusive modules (ie no pipeline instance
will involve more than  one module instance with one of these names). However, we
may or may not enforce that. We could throw an error if it is not true, or we could simply ignore pipelines containing more than one of them.  Actually we should probably throw an error unless a flag is set to force that ignoring behavior.

So let's take one at a time. I'll take the second one first as it is simplest
`(mean,median) .name`
Here `(mean,median)` species a condition: 
we want to select the subset of  pipeline instances that include 
exactly one module instance whose name is in the set ("mean","median").  

The `.name` means that a column of output will be produced that contains the name of the module instance satisfying this condition.

Now: `(score_beta) .name .output:score`

Again `(score_beta)` specifies the condition,
we want to select the subset of  pipeline instances that include 
exactly one module instance whose name is in the set ("score_beta").  

And `.name .output:score' indicate two output columns, first the name of the module that
satisfies the condition, and second the value of the output variable 
$score in the output of that module.
(Optional enhancement: 
if the module with that .name does not output $score then we could go back up the pipeline 
instance to the last module instance that did output a variable called $score and output that. )

Finally:
`(norm,t,cauchy) .name .param:n WHERE .param:n IN (10,100)`
Again `(norm,t,cauchy)` specifies the condition, 
we want to select the subset of  pipeline instances that include 
exactly one module instance whose name is in the set ("norm","t","caucy").  
But now this is enhanced by the WHERE statement, that the value of the parameter n in
that module instance must be either 10 or 100

EDIT: implicit here is that every one of those modules `(norm,t,cauchy)` must have  a
parameter named n. If not then we can throw an error. (And maybe? have a flag to override this -
in which case here such pipelines would be excluded as they automatically
do not satisfy the WHERE condition.. they would have column param.n=NA if the WHERE were absent). 

The output will also include a column "seed" which will be the seed value set
before the pipeline instance was executed.

Since we will almost always want to output the name of the module we could assume that
as default to simplify syntax:

``` 
-e 
(norm,t,cauchy) .param:n WHERE .param:n IN (10,100),
(mean,median),
(score_beta) .output:score
```

**Comment by gaow** [comment]
Thanks @stephens999. Sorry I'd like to start by saying I should not insist on non-R / command line based syntax. If DSC's first target user are people from our lab we should **definitely** develop an R syntax (that you've suggested in the document but have not expanded to more difficult scenarios). I fear of designing an R interface on my own because it might end up looking very much like SQL or something else I'm more familiar with, even though it's an R function ... that's why I was hoping at least someone from the R camp can device the interface assuming I can implement it one way or another using whatever technique (SQL, dplyr, etc). I apologize giving you the impression that I'm insisting on SQL-like style and made you propose an interface in that flavor ... 

Your comments in this post lists what we want to input and what we expect as output, which is great. I get most part. My comments / doubts:

> To simplify, think for a moment that the result of this query will be a table/dataframe, with one row per pipeline instance. 
> ...
> Each element of the extraction defines a subset of pipeline instances and some columns of output to be produced. The overall result will be the intersection of the rows and union of the columns.

So organization-wise it should be very similar to the `master` tables in meta-data, with additional columns added to it being mostly parameters?

> (For more complex queries involving non-atomic results we will need to use a list).

For non-atomic results we can still have a table plus a list where in the table instead of storing the value(s) in the result column we store the index to the list -- or do you know any other way that makes organizing / accessing the non-atomic objects easier? Storing index of lists seems something very basic but perhaps there are more modern R data structure we can use?

> The output will also include a column "seed" which will be the seed value set
before the pipeline instance was executed.

This is by default? then the columns will have to be named something like `.name_seed` perhaps for every module because we do allow for the potential that each module has their own seeds #70. The only simplification I can think of is to use a `seed` column for the pipeline seed and only add `.name_seed` if the module specific seed is different from the pipeline seeds. 

The interface you proposed is quite SQL-like therefore it should not be very hard to migrate from my current Python codes. But again I apologize and I'm saying it should be more R like, and we want to use it from within R not the terminal, just for the sake of our people. However I do recall the SQL library that R has is from bioconductor and it is not straightforward to install. I've only took a glance at `dplyr` -- certainly not as powerful as SQL but we should be able to make do with that, for our application.

**Comment by gaow** [comment]
I'm reading your R interface again, but I cannot directly translate it to the SQL-like flavor that you've proposed:

```
res = create_data_frame(p, scenario =c(norm,t), method=c(mean, median), score = score, n= c(norm$param$n, t$param$n))
```

I can expand it to the SQL-like syntax but I do not think it is as logically clear. If we can focus on devising an R interface that essentially conveys the same information you previously posted, in a nice and clear way, then we should be making a big step forward.

**Comment by stephens999** [comment]
i think my command line suggestion is more developed (and cleaner) than
my previous R suggestion as my thinking evolved over the last couple
of days of discussion...

I'm really fine with initial command line interface to create an rds
file to read into R! I believe your current -e command produces an RDS
file?

Ideally I would like that rds file to be a dataframe when the
extraction is simple enough to be represented by a dataframe.

**Comment by stephens999** [comment]
> The only simplification I can think of is to use a seed column for the
pipeline > seed and only add .name_seed if the module specific seed is
different from > the pipeline seeds.

I envisage only outputting the pipeline seed by default,
even if the module seeds
are different, as module seeds will not be interesting usually - only for
debugging maybe.
I would allow the user to require outputting the module instance seed in
the -e
by for example
-e (norm,t) .name .seed

**Comment by gaow** [comment]
Yes my `-e` command will create RDS file but 

1. By default is not a flat table, due to non-atomic objects. 
2. The syntax of the command line is not SQL-like. Rather an annotation file has to be used and SQL-like queries will be translated from the annotation file. 

I adopted the annotation file design because it looks very similar to DSC file in syntax. With the command syntax you propose here I think we can get rid of annotation files. We can remove `dsc -a` and change `dsc -e`  to take these syntax directly rather than results from annotation. It will not make a big change to the `preview` panel of shinydsc that @NKweiwang has developed.

The major difference between your syntax and SQL is that in yours you have hide the "INNER JOIN ... ON ..." part, taken that for granted. Otherwise it's almost SQL. Now the question is how far we want to take it down the road of SQL. I can potentially make it very flexible by just adopting direct SQL syntax at least for the `WHERE` part so that users can make complicated queries. The challenge is that the more advanced `WHERE` is then more arbitrary other module tables it will involve, and propagating these `INNER JOIN ... ON ...` statements automatically and correctly will get harder.

**Comment by stephens999** [comment]
i would not remove  dsc -a for now... possibly it will be useful for more complex settings.
Alternatively if you think about implementing (in the future) a "very flexible" approach
based on direct SQL syntax, maybe dsc -a is the place to think about doing that?
I think my proposed -e approach could always be combined with tags from dsc -a if it
were desired later...

But for now I hope the dsc -e approach will fulfill most of our needs.

**Comment by gaow** [comment]
Discussion formalized at:

https://github.com/stephenslab/dsc-wiki/blob/master/development/finalized_terminology_and_extraction.md
