### ISSUE TITLE
formal definition of module

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc2#73]
@gaow @pcarbo 

I'm opening a separate ticket for this because I feel the terminology ticket is more general
and perhaps less formal. And as @pcarbo suggested it might be useful to have a discussion in more
formal terms. Also I think this discussion could have potential implications for the yaml syntax
and perhaps how we actually define modules in practice in dsc.

Here is my first try (I'm really not sure i know enough of the right terminology to do this, so
@pcarbo feel free to suggest improvements/corrections!)

In essence, a module (definition)
is simply a computational procedure with formal arguments `$i1, $i2, ...` 
whose output is an environment containing variables `$o1, $o2,...` and their values.
( and no side effects?)

The way we *define* such a module in the YAML file is motivated by the idea that typically
we already have a procedure or function `f`, defined elsewhere (eg in base R or an R package), that accomplishes most of what we want our module to accomplish, 
but with different formal arguments. Effectively we
are just providing a convenient way to provide a wrapper to `f`.

Specifically we define:
- a function (or procedure) `f`, with formal arguments `x1, x2, ...` that returns an environment
with variable names `y1, y2, ...` and their values.
- a set of input variable names `$i1, $i2, ...` 
- a set of output variable names `$o1, $o2, ...`
- a parameter environment, containing variables with names `p1, p2...` 
and their corresponding values
- a mapping `I` (for input) from `($i1,$i2..., p1,p2,...) -> (x1,x2,...)` that maps input variables and parameters map to the formal arguments of `f`.
- a mapping `O` (output) from `(y1,y2...) -> ($o1,$o2...)` that maps an output from `f` to the output variables

An instance of the module is created by first setting a random seed,
 and then invoking the module with an 
input environment with variables `($i1,$i2,...)` and their values.
It produces the output environment with variables `($o1,$o2,...)` and their values 
`($o1,$o2,...) = O(f(I($i1,$i2,...,p1,p2,...)))`

Note that currently DSC does not require the function `f`, or its arguments, 
to be formally defined. It is all implicit right now. But it might be useful to require this.
The yaml defines the mappings I and O, and the parameter environment.

Although the above is pretty verbose, one could imagine a very succinct way to describe
some things. 

For example a module called "normal" could be defined by something like 
``normal: $x = rnorm(n = 1000, m=$mean, sd=1)``

could be used to define that:

- `f =rnorm(),` the standard R function, 
- input variables are `$mean`
- output variables are `$x`
- params `p` is `(n=1000,sd=1)`
- mapping `I` is `$mean, n,sd -> m,n,sd`
- mapping `O` is the unnamed output of rnorm -> $x. (hmm.. rnorm doesn't quite my definition above before the output is unnamed).

Of course the current YAML does not allow this, but I'm hopeful we might be able to in the future.

**Comment by gaow** [comment]
Thanks @stephens999 it's a good time to start these thread and again I find concrete example useful. Speaking of example:

```
normal: $x = rnorm(n = 1000, m=$mean, sd=1)
```
looks very tempting but is perhaps overly succinct and restrictive.

> Note that currently DSC does not require the function f ... But it might be useful to require this.

I'm not sure about this. You essentially require all computational routines have to be one main function call. But currently one can also write [loose lines of codes](https://github.com/stephenslab/dsc2/blob/master/vignettes/one_sample_location/R/methods/median.R), classes (not function calls, for Python) and even just running one executable for terminal commands. I do not think it's necessary to wrap function calls around everything.

> f =rnorm(), the standard R function

DSC should not interpret a specific language unless asked. So you'll have to use

`R(rnorm(n = 1000, m=$mean, sd=1))` (wont work for now due to `$mean`)

Also this design makes it almost impossible to track parameter assignment and create the meta-data, because it makes parsing very hard. This example is fine as I can perhaps take whatever inside `rnorm()` (if I know it's a function call), split by `,` and harvest for each element the right hand-side of values, try to determine their data type (str, number), etc. But it gets complicated very easily, for example when one type:

```
normal: $x = f(n = 1000, c($mean, 1))
```
That not only I'll not tell what the name of parameters are. Yet this statement looks very much legit R syntax at a glance. Even if it is named, 

```
normal: $x = f(n = 1000, param = c($mean, 1))
```

I will not be able to parse `c()` because it's R specific and DSC would not know it. In Python it should be

```
normal: $x = f(n = 1000, param = ($mean, 1))
```

Also this syntax does not address my concern when multiple similar modules are to be executed with multiple parameters in a combinatoric fashion.

**Comment by gaow** [comment]
I think we should focus on the weakness of current YAML format and work from there. To me the biggest problem is that multiple parameters have to be in multiple lines, making it verbose:

```
simulate:
  exec: datamaker.R
  params:
     n : 10, 20
     m: 3
     s: 0.1, 0.2
```

I can imaging improving it to 

```
simulate:
  exec: datamaker.R
  params: n = 10, 20; m = 3; s = 0.1, 0.2 
```

(parsing will still be hard because you cannot rely on `;` or `=` as the separator eg. 

`params: var = I=want;to,cause;==you;;trouble=::`

This is why I started with strict multi-line YAML. But we can think harder about it.

**Comment by gaow** [comment]
@stephens999 and I had a quick in person meeting summarized below:

1. We do want to allow for using different parameter combinations under the same module name, although conceptually they will be referred to as different modules. For example:

```
simulate: datamaker.R
   params:
     K: 2, 4
     N: 100, 200
```
Will result in 4 modules each taking a combination of parameters.

2. We replace the old concepts of `block` and `step` by `modules`, and we discard the keywords `exec` and `alias`. So the old syntax:

```
shrink: 
   exec: ash.R, ash.R
   .alias: ash.n, ash.hu
```
is now:

```
ash.n, ash.hu: ash.R
```

3. We allow for some default shortcut to name modules. This holds only when there is at most one parameter or executable that iterates. For example, previously:

```
ash.n, ash.hu: ash.R
   params:
     exec[1]: 
       method: normal
     exec[2]:
       method: halfuniform
```
will now look like:

```
ash.n, ash.hu: ash.R
   params:
      method: normal, halfuniform
```
Although the first specification is also valid. It's a matter of style choice although we can recommend good practice to people.

4. We have not agreed on if we do want to force people to wrap things in functions. My major concern is executables being terminal commands not scripts. Will use a separate issue to explain it.

5. This is not what Matthew and I dsicussed and it is minor but I think I should improve the parser to be smart enough to use 

```
ash.n, ash.hu: ash.R
   params:
     ash.n: 
       method: normal
     ash.hu:
       method: halfuniform
```
Instead of indexing by `exec[i]`. Should not be too hard. 

Finally my only concern (more a question to myself) is what I should do with block derivation. I found it a great feature that makes things a lot simpler. For single module case it still holds:

```
ash.n: ash.R
   params: 
     method: normal
     other_params: ....
   return: x

ash.hu(ash.n):
   params: 
      method: halfuniform
```
But for the multiple module case `ash.hu, ash.n` it is a bit harder / awkward if another module want to derive from it.

**Comment by stephens999** [comment]
For that last example would seem to make more sense to start with a
definition of a single module ash, and then derive ash.n and ash.u from it?

**Comment by gaow** [comment]
Yes one can define a module `ash` and derive from it both `ash.n` and `ash.hu` -- it's a choice of style that we can only suggest but not reinforce. I think I should also support derivations such as:

```
ash.n1, ash.hu1 (ash.n, ash.hu): ash.R
```
Where the new modules are derived from a multi-module code block.

**Comment by stephens999** [comment]
this kind of functionality can be helpful, but I see it as mostly
a "convenience", not essential.

**Comment by gaow** [comment]
Discussion formalized at 

https://github.com/stephenslab/dsc-wiki/blob/master/development/finalized_terminology_and_extraction.md
