### ISSUE TITLE
Query based on input / output

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#77]
## Can we query based on input / output?

Not for now, because pipeline variables are generated only at execution, and are passed along in DSC via files. They are basically "capsuled". However with additional work we can query on them, ie, make a first query without these conditions, then for each RDS file involved so far, we load it from disk, compare it with the condition, and drop the entire row (of pipeline instance) if it does not satisfy it. It would not need us to change our design to make it happen. Just some post-processing.

When this is supported we have to use `$` to refer to pipeline variables in queries.

**Comment by stephens999** [comment]
I agree with all this. It just makes me wonder
whether to choose a different symbol than $ because
of its special use in R for element of a list...

that is, if we got to the point of having an object
representing the results of a pipeline in R, and we wanted
to refer to the $x value, we might have res[["$x"]] rather than res$x.
I'm not sure if $ is even a valid way to start a variable name in R.
(maybe this is why we chose $?!)

I actually like the $ , partly because of its association with wildcards,
and in a way the pipeline variables play a role somewhat
analogous to wildcards in make files...  But something to think about.

**Comment by gaow** [comment]
I'm not sure if we have a need to change `$` for something else. The query interface I have in mind is strictly `module.variable` theme, or `module:variable`. So if we eventually support pipeline input/output based query, we would use `module.$variable` or `module:$variable` for pipeline variables to distinguish them. 

In other scenarios we do not allow for `module.variable` theme because which `module` a `$variable` comes from is is implicitly determined. I'd rather stick to this implicit feature unless there is a convincing case to persuade me otherwise.

> I'm not sure if $ is even a valid way to start a variable name in R.

It is not valid. I started using `$` because it seems to be a widely accepted wildcard symbol.

**Comment by stephens999** [comment]
Ok, I'm good with keeping $
