### ISSUE TITLE
several wiki links broken

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc2#85]
several of the documentation links at the bottom of the home page don't seem to work...

**Comment by gaow** [comment]
The broken links are result of migrating loosely organized notebooks to using `jnbinder` (https://github.com/stephenslab/ipynb-website) so there are URL changes.

`jnbinder` provides a utility to check broken links so it is very easy to identify them though changing them all should take about an hour. I'm going to do it later today since it is important to the proposal review.
